### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by melinjo** [pixelimity/pixelimity#1]
Baru nyoba di install di localhost pakai wamp, langsung error
muncul pesan 500 Internal Server Error

**Comment by kodercupu** [comment]
errornya pas udah install atau sebelum install mas? versi WAMP berapa mas?

**Comment by melinjo** [comment]
errornya setelah ngisi form instalasi,
wamp nya versi 2.4

**Comment by kodercupu** [comment]
PHP dan MySQL versi berapa mas?

**Comment by melinjo** [comment]
php nya versi 5.4.16
mysql nya versi 5.6.12
apache nya versi 2.4.4

**Comment by kodercupu** [comment]
setelah muncul error apakah file _config.php_ sudah ada di folder _install_ ?

**Comment by melinjo** [comment]
iya, sudah
di dalam folder install ada 4 file, config.php, config-sample.php, db.sql, sama index.php

**Comment by kodercupu** [comment]
pas akses home-nya masih error mas?
db-nya udah dibuat kan?

**Comment by melinjo** [comment]
databasenya sudah saya buat, dikasih nama pixelimity kan ? 
maksudnya akses home-nya itu gmna mas ?
saya akses-nya begini http://localhost/pixelimity, dan hasilnya masih 500 Internal Server Error
apakah baru saya mas yang laporan seperti ini ?

**Comment by kodercupu** [comment]
iya mas. 
ada partner saya yang make WAMP aman-aman aja kok

**Comment by septyaman** [comment]
Coba cek PHp my adminnya, apakah db pixelimity ter update datanya atau masih kosong?

**Comment by adamramadhan** [comment]
mending kaya kasih error reporting -1 biar keliatan semua sebelum sampai selesai install.
