### ISSUE TITLE
Review and Idea

### ISSUE THREAD

**Issue by bepitulaz** [pixelimity/pixelimity#4]
Hello there,

I had been installing your cms. Great job, Guys. Below, I'm sharing my review of Pixelimity:
1. Create portfolio by saving the portfolio first then upload the image is too hassle. Why you don't make it in one step?
2. Why you don’t provide a date picker?
3. Please don’t put 404 error message as default message after installing the CMS. User will be confused; they will assume there’s an error. Maybe better if you put something informative e.g., "Hello, you can start publish your first portfolio". Just my thought.

Thanks.

**Comment by takien** [comment]
Thanks for your review and feedback.
We really appreciate it.
