### ISSUE TITLE
Trailing slash di HTTP_HOST

### ISSUE THREAD

**Issue by bangbambang** [pixelimity/pixelimity#9]
> OS: Windows 7 32bit.
> Env: Apache/2.2.21 (Win32) mod_ssl/2.2.21 OpenSSL/1.0.0e PHP/5.3.8 mod_perl/2.0.4 Perl/v5.10.1
> Versi: de083b93fd2e37dfc798b62e21adb5767d82501c

Di file `config.php` dan `install/index.php`, di bagian:

``` php
    define ('URL', 'http://'. $_SERVER['HTTP_HOST'] . PATH);
```

`$_SERVER['HTTP_HOST']` tidak ditambah trailing slash. Sehingga ketika dilakukan pemasangan di subdirektori, `URL` menjadi invalid.

Bisa diperbaiki dengan mengubah kode diatas menjadi:

``` php
    //Sesuai minimum req. (PHP 5.3), menggunakan strlen() bukan 
    //empty() (ref: http://3v4l.org/3M5oN )
    if(strlen(PATH) > 0) {
        define ('URL', 'http://'. $_SERVER['HTTP_HOST'] . '/' . PATH);
    } else {
        define ('URL', 'http://'. $_SERVER['HTTP_HOST']);
    }
```

Apakah perlu dibuatkan pull request? Atau ada cara yang lebih baik?

**Comment by ianmustafa** [comment]
Pull request aja, default pake trailing slash. Ga usah kasih conditional statement, kurang efektif menurut ane

**Comment by takien** [comment]
ya, pull request.

**Comment by bangbambang** [comment]
PR sudah dikerjakan, mohon reviewnya om @cuplizian dan om @takien.
Sebagai tambahan, masalah ini ternyata gara-gara `$_SERVER['DOCUMENT_ROOT']` di XAMPP yang tidak menyertakan trailing slash (bukan masalah di `$_SERVER['HTTP_HOST']` seperti yang disampaikan sebelumnya).
Maaf atas kesalahan informasinya, dan terima kasih. :pray:

**Comment by takien** [comment]
E̶h̶ ̶u̶d̶a̶h̶ ̶s̶a̶y̶a̶ ̶m̶e̶r̶g̶e̶,̶ ̶t̶a̶p̶i̶ ̶b̶l̶o̶m̶ ̶s̶a̶y̶a̶ ̶t̶e̶s̶t̶ ̶d̶i̶ ̶n̶o̶n̶ ̶X̶A̶M̶P̶P̶ ̶:̶3̶ ̶
tested.
